security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        # Charge les utilisateurs à partir de la base de données
        database_users:
            entity:
                class: App\Entity\User
                property: email  # Le champ utilisé pour l'identification (email)
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: database_users  # Utilisation du fournisseur basé sur la base de données

            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
                default_target_path: /dashboard  # Après connexion réussie, redirection vers le dashboard
            logout:
                path: /logout
                invalidate_session: true  # Déconnexion et invalidation de la session
            
            remember_me:
                secret: '%kernel.secret%'  # Clé secrète pour le "remember me"

            # Stateless peut être activé pour ne pas utiliser les sessions si tu veux utiliser des tokens
            stateless: false  # Activer les sessions

    access_control:
        # Protège les routes avec des rôles spécifiques
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
